### ISSUE TITLE
postgres - can't connect to schema when table in schema has foreign key constraint to table in different schema

### ISSUE THREAD

**Issue by ryantuck** [pudo/dataset#170]
fresh postgres database (named test):

``` sql
create schema a;
create schema b;

create table a.foo (id integer, name text);
create table b.bar (id integer, name text);

alter table a.foo add constraint x unique (id);
alter table b.bar add constraint y foreign key (id) references a.foo (id);
```

then in python:

``` python
import dataset
db = dataset.connect('postgres://me:my_password@localhost:5432/test', schema='b')
```

full stack trace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/dataset/__init__.py", line 42, in connect
    ensure_schema=ensure_schema, row_type=row_type)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/dataset/persistence/database.py", line 62, in __init__
    self.load_table(self.metadata.tables[table_name].name)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/dataset/persistence/database.py", line 239, in load_table
    schema=self.schema, autoload=True)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/sql/schema.py", line 416, in __new__
    metadata._remove_table(name, schema)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/sql/schema.py", line 411, in __new__
    table._init(name, metadata, *args, **kw)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/sql/schema.py", line 484, in _init
    self._autoload(metadata, autoload_with, include_columns)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/sql/schema.py", line 508, in _autoload
    self, include_columns, exclude_columns
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/base.py", line 1972, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/base.py", line 1477, in run_callable
    return callable_(self, *args, **kwargs)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/default.py", line 364, in reflecttable
    return insp.reflecttable(table, include_columns, exclude_columns)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/reflection.py", line 563, in reflecttable
    table_name, schema, **table.dialect_kwargs):
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/reflection.py", line 369, in get_columns
    **kw)
  File "<string>", line 2, in get_columns
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2376, in get_columns
    info_cache=kw.get('info_cache'))
  File "<string>", line 2, in get_table_oid
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/ryan/Library/Python/2.7/lib/python/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2274, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: foo
```

---

_but i found a workaround_

not that familiar with `sqlalchemy`, but it seems that adding `reflect_metadata=False` as an arg will allow the connection to go through. 

is this a bug, and is it necessarily a bug in `dataset` or `sqlalchemy`? either way, hope this issue helps somebody else going forward.

**Comment by ryantuck** [comment]
update - even though i can connect to the schema, attempting to read/write to/from the table yields another similar error:

`NoSuchTableError: foo`

**Comment by pudo** [comment]
Just tried to replicate this and it seems our schema handling is OK now, closing.
