### ISSUE TITLE
Case sensitive column in mysql is not working

### ISSUE THREAD

**Issue by rumchang** [pudo/dataset#188]
I created a table in mysql
```sql
create table if not exists test_dataset (
    testId int primary key,
    testName varchar(128)

);
```
Then I tried to upsert data into that table using dataset 0.7.0
```python
import dataset

url = 'mysql://user:pswd@host/db'
db = dataset.connect(url, 
    reflect_metadata=False, 
    engine_kwargs={'pool_recycle': 3600, 'case_sensitive': False}
)
table = db['test_dataset']
data = {'testId': 1, u'testName': "dataset"}
table.upsert(data, ['testId'], ensure=False)
```
But an exception occurred
```
Traceback (most recent call last):
  File "test_dataset.py", line 11, in <module>
    table.upsert(data, ['testId'], ensure=False)
  File "/usr/local/lib/python2.7/site-packages/dataset/persistence/table.py", line 227, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/usr/local/lib/python2.7/site-packages/dataset/persistence/table.py", line 87, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/base.py", line 1003, in _execute_clauseelement
    inline=len(distilled_params) > 1)
  File "<string>", line 1, in <lambda>
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/elements.py", line 494, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/elements.py", line 500, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 392, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 190, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 213, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/compiler.py", line 1819, in visit_insert
    crud_params = crud._get_crud_params(self, insert_stmt, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/sql/crud.py", line 109, in _get_crud_params
    (", ".join("%s" % c for c in check))
sqlalchemy.exc.CompileError: Unconsumed column names: testid, testname
```
I know that dataset uses `normalize_column_name` to normalize column name into lower case and sqlalchemy's default `case_sensitive=True`  in [create_engine](http://docs.sqlalchemy.org/en/latest/core/engines.html#engine-creation-api) since version 0.8. But since I used `'case_sensitive': False` in `engine_kwargs` when connecting, I don't know how this exception happened.

BTW, Is there a little confusion that sqlalchemy's default `case_sensitive=True` while dataset uses `normalize_column_name` to normalize column name to lower case?

Thanks a lot.

**Comment by pudo** [comment]
Yes, looks like ``normalize_column_name`` (or the more general schema caching) is inconsistent with MySQL in case insensitive mode. Would you like to have a stab at a PR?

**Comment by rancas** [comment]
Hi,

I have the same issue as @rumchang 
I found the point where the code should be changed:
https://github.com/pudo/dataset/blob/master/dataset/persistence/util.py#L41

could it just be changed to:
`
name = name.strip()
`

in order to allow for Upper case column names?
