### ISSUE TITLE
TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [pudo/dataset#212]
Hi. I really like the concept of dataset but I'm having a problem using it on my sqlite db.

Simple code
```python
db['parts'].find(import_successfully=True)
for r in rows:
      print(r['description'])
```

sqlite3 table
```sql
CREATE TABLE IF NOT EXISTS parts (
  description TEXT,
  file BLOB,
  reference BLOB,
  tolerance TEXT,
  units TEXT,
  import_successfully BOOL,

  last_success_test_time TEXT,
  status TEXT
);
```

```shell
Traceback (most recent call last):
  File "test_nesting_methods.py", line 142, in test_create_shape_errors
    for r in rows:
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dataset/persistence/util.py", line 70, in __next__
    return convert_row(self.row_type, next(self._iter))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dataset/persistence/util.py", line 35, in convert_row
    return row_type(row.items())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sqlalchemy/engine/result.py", line 166, in items
    return [(key, self[key]) for key in self.keys()]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sqlalchemy/engine/result.py", line 166, in <listcomp>
    return [(key, self[key]) for key in self.keys()]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sqlalchemy/sql/sqltypes.py", line 904, in process
    value = bytes(value)
TypeError: string argument without an encoding
```

**Comment by pudo** [comment]
This must be related to the BLOBs. Do you have a testing database you could share?

**Comment by BebeSparkelSparkel** [comment]
[dataset.db.zip](https://github.com/pudo/dataset/files/1275418/dataset.db.zip)

**Comment by stefanw** [comment]
I can reproduce on Python 3. The error is coming out of sqlalchemy which is calling `bytes` on a unicode string without giving an encoding. Why it gets a unicode string from the db is not clear to me:

```python
>>> db['parts']._table.columns['file']
Column('file', BLOB(), table=<parts>)
```

In Python 3, inserting `bytes` in a `dataset` Table creates a Text column in sqlite3. However, it will still give `bytes` back because it is apparently stored differently. Here's a `.dump` from a test:

```sql
CREATE TABLE new_table (
	id INTEGER NOT NULL, byte_col TEXT, str_col TEXT,
	PRIMARY KEY (id)
);
INSERT INTO "new_table" VALUES(1,X'6279746573',NULL);
INSERT INTO "new_table" VALUES(2,'no bytes','no bytes');
COMMIT;
```

The value of `X'6279746573'` translates to `b'bytes'` in Python 3 which is what was inserted.

So in Python 3, if you started from scratch without a BLOB type column and just inserted regular bytes, you appear to get bytes back. [I build a test for inserting `bytes` and it only fails on Python 2](https://travis-ci.org/pudo/dataset/builds/281269040)
