### ISSUE TITLE
problem explicitly adding column to table prior to any write

### ISSUE THREAD

**Issue by paulfitz** [pudo/dataset#220]
I'm seeing a problem (with dataset==1.0.0) explicitly creating columns like this:
```py
    def test_create_table_and_add_column(self):
        table = self.db.create_table('addresses')
        table.create_column('status', self.db.types.integer)
        assert len(table.table.columns) == 2, table.table.columns
```
The above code fails as follows:
```py
Traceback (most recent call last):
  File "/home/paulfitz/cvs/dataset/test/test_dataset.py", line 154, in test_create_table_and_add_column
    table.create_column('status', self.db.types.integer)
  File "/home/paulfitz/cvs/dataset/dataset/table.py", line 334, in create_column
    self.db.schema
  File "/usr/local/lib/python2.7/dist-packages/alembic/operations.py", line 595, in add_column
    schema=schema
  File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 176, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python2.7/dist-packages/alembic/ddl/impl.py", line 122, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
    compiled
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (pysqlite2.dbapi2.OperationalError) no such table: addresses [SQL: u'ALTER TABLE addresses ADD COLUMN status INTEGER']
```
If I write something before adding a column, all is good - for example, this works:
```py
    def test_create_table_and_add_column(self):
        table = self.db.create_table('addresses')
        table.insert({})  # <--- adding a write
        table.create_column('status', self.db.types.integer)
        assert len(table.table.columns) == 2, table.table.columns
```
I see a commit message related to lazy table creation, and I'm guessing this is a side effect of that. Should I change how I'm writing the code or is there a bug?

Great library and excited to see it reach 1.0 :-)

**Comment by pudo** [comment]
Thanks a lot for reporting this so clearly, it's indeed a bug resulting from the lazy table creation. I will make it a 1.0.1 :)
