### ISSUE TITLE
Python 3 JSON Freeze errors out

### ISSUE THREAD

**Issue by ColdHeat** [pudo/dataset#227]
I'm running into an issue with Python 3 and dataset where it is unable to export a table to JSON using Python 3.6: 

```
Traceback (most recent call last):
  File "export.py", line 12, in <module>
    backup = export_ctf()
  File "/Users/kchung/Repositories/CTFd/CTFd/utils.py", line 639, in export_ctf
    datafreeze.freeze(result, format='json', fileobj=result_file)
  File "/Users/kchung/.virtualenvs/ctfd3/lib/python3.6/site-packages/datafreeze/app.py", line 124, in freeze
    return freeze_export(Export({}, kw), result=records)
  File "/Users/kchung/.virtualenvs/ctfd3/lib/python3.6/site-packages/datafreeze/app.py", line 136, in freeze_export
    serializer.serialize()
  File "/Users/kchung/.virtualenvs/ctfd3/lib/python3.6/site-packages/datafreeze/format/common.py", line 93, in serialize
    self.close()
  File "/Users/kchung/.virtualenvs/ctfd3/lib/python3.6/site-packages/datafreeze/format/fjson.py", line 61, in close
    fh.write(data)
TypeError: a bytes-like object is required, not 'str'
```

I'm technically using datafreeze at the moment but I think the codebases are reasonably similar but I can open the issue there if you prefer.

**Comment by pudo** [comment]
Wrong repo, closing here.
