### ISSUE TITLE
dataset requires mysql-python to work with MySQL

### ISSUE THREAD

**Issue by abelsonlive** [pudo/dataset#25]
I get this error when I use `dataset` without the `MySQLdb` module installed:

```
Traceback (most recent call last):
  File "freeze_data.py", line 7, in <module>
    db = dataset.connect(config['db_path'])
  File "/Library/Python/2.7/site-packages/dataset-0.3.8-py2.7.egg/dataset/__init__.py", line 29, in connect
    return Database(url, schema=schema, reflectMetadata=reflectMetadata)
  File "/Library/Python/2.7/site-packages/dataset-0.3.8-py2.7.egg/dataset/persistence/database.py", line 36, in __init__
    engine = create_engine(url, **kw)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/__init__.py", line 332, in create_engine
    return strategy.create(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/sqlalchemy/engine/strategies.py", line 64, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/Library/Python/2.7/site-packages/sqlalchemy/connectors/mysqldb.py", line 57, in dbapi
    return __import__('MySQLdb')
ImportError: No module named MySQLdb
```

which is easily solved with:

```
pip install mysql-python
```

**Comment by brandonlipman** [comment]
I get this error when running `pip install mysql-python`: 
`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3n/9mpgpd6n1055xppx1m6zk8zw0000gn/T/pip-build-fuiruk/mysql-python/`

Have tried running `sudo pip install MySQL-python` and several other things and I still get the same error when installing and when trying to create a MySQL database using Dataset.

**Comment by stefanw** [comment]
`dataset` does not come with database drivers (except sqlite3 which comes with Python).

You need to install your own database driver and we cannot help you with that. [Please refer to the SQLAlchemy documentation](http://docs.sqlalchemy.org/en/latest/dialects/).
