### ISSUE TITLE
connect() doesn't work on Path objects

### ISSUE THREAD

**Issue by apnewberry** [pudo/dataset#279]
[As of Python 3.7](https://bugs.python.org/issue33496), `sqlite3.connect(path)` accepts Pathlike objects like `pathlib.Path`. This doesn't work in dataset.

```
>>> import dataset, pathlib
>>> dataset.connect(pathlib.Path('db'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.envs/env/lib/python3.7/site-packages/dataset/__init__.py", line 42, in connect
    ensure_schema=ensure_schema, row_type=row_type)
  File "/home/user/.envs/env/lib/python3.7/site-packages/dataset/database.py", line 35, in __init__
    parsed_url = urlparse(url)
  File "/usr/lib/python3.7/urllib/parse.py", line 367, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/lib/python3.7/urllib/parse.py", line 123, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/lib/python3.7/urllib/parse.py", line 107, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/lib/python3.7/urllib/parse.py", line 107, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'PosixPath' object has no attribute 'decode'

```

**Comment by Red-Eyed** [comment]
It seems that it's not a bug, as string is supposed to be with a prefix like `'sqlite:///mydatabase.db'`, not a Path

**Comment by pudo** [comment]
What @Red-Eyed said.

**Comment by Ashebir07** [comment]
You can easily configure the database directories 
DATABASES = {
    "default": config(
        "DATABASE_URL", default="sqlite:///" / BASE_DIR / "db.sqlite3", cast=db_url
    )
}
