### ISSUE TITLE
Do I have to remove None values from dicts when I add them?

### ISSUE THREAD

**Issue by everythingability** [pudo/dataset#316]
I'm trying to bang a dict straight into a usertable like this... and I remove all the None values but it still errors.. I'm using SQLite

```
for person in result['person']:
	print( person['href'] )

	# CLEAN UP THE DICTS
	links = person['links']	
	del person['links']
	
	newDict = {}

	for p in person:
		print( p, person[p])
		if person[p] != None :
			newDict[p] = person[p]
	
	print(newDict)
	usertable.insert( newDict )
```

....and I get this... 

```
{'id': '60901274-0148-4EBB-9461-9B6FD0090598', 'href': 'https://gtr.ukri.org:443/gtr/api/persons/60901274-0148-4EBB-9461-9B6FD0090598', 'created': 1582643294000, 'firstName': 'Hui', 'otherNames': '', 'surname': 'Yuan'}
Traceback (most recent call last):
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: datatype mismatch

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "get_people.py", line 35, in <module>
    usertable.insert( newDict )
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/dataset/table.py", line 111, in insert
    res = self.db.executable.execute(self.table.insert(row))
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/Users/tomsmith/gtr_object_definitions/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) datatype mismatch
[SQL: INSERT INTO users (id, href, created, "firstName", "otherNames", surname) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('60901274-0148-4EBB-9461-9B6FD0090598', 'https://gtr.ukri.org:443/gtr/api/persons/60901274-0148-4EBB-9461-9B6FD0090598', 1582643294000, 'Hui', '', 'Yuan')]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

Thanks

**Comment by everythingability** [comment]
Ahhhh!  Got it... one key was called id but it is a string... This works... 

```
	for p in person:
		print( p, person[p])
		if person[p] != None :
			if p == 'id':
				newDict[p+"_str"] = person[p]
			else:
				newDict[p] = person[p]

```

**Comment by pudo** [comment]
By default, `dataset` will create an `id` on each table and make it an integer. You can prevent this by passing the following argument when you first fetch the table: 

```python
database.get_table('blah', primary_id=False)
```
